export const GET_DATA_REQUEST = "GET_DATA_REQUEST"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAILUER = "GET_DATA_FAILUER"

export const ADD_DATA_REQUEST = "ADD_DATA_REQUEST"
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS"
export const ADD_DATA_FAILUER = "ADD_DATA_FAILUER"

export const UPDATE_DATA_REQUEST = "UPDATE_DATA_REQUEST"
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS"
export const UPDATE_DATA_FAILUER = "UPDATE_DATA_FAILUER"

export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST"
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS"
export const DELETE_DATA_FAILUER = "DELETE_DATA_FAILUER"